name: dart_wif
description: Dart Bitcoin Wallet Import Format encoding/decoding package.
version: 1.1.0
homepage: https://github.com/dart-bitcoin-lib/dart-wif

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  dart_bs58check: ^1.1.0
  convert: ^3.0.1


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0